name: Build Calibration FE

on:
  push:
    branches: [calibration]

env:
  SLACK_CHANNEL: infra-ci-filplus
  AWS_REGION: us-east-1
  S3_BUCKET: dev-calibrationfilplusdinterplanetaryone-origin
  CDN_NAME: calibration.filplus.d.interplanetary.one
  BUILD_ENVS: |
    REACT_APP_API_BASE_URL="https://api.calibration.filplus.d.interplanetary.one/api"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cristi-mb/build-fe@main
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          aws-s3-name: ${{ env.S3_BUCKET }}
          aws-cloudfront-name: ${{ env.CDN_NAME }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          build-envs: ${{ env.BUILD_ENVS }}
